trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Test
    displayName: Run Test
    jobs:
      - job: UnitTest
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              jdkVersionOption: '1.8'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              mavenAuthenticateFeed: false
              mavenVersionOption: 'Default'
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  - stage: Deploy
    displayName: Run Deploy
    jobs:
      - job: DeployArtifact
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'deploy'
              publishJUnitResults: true
              jdkVersionOption: '1.8'
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              mavenAuthenticateFeed: true
              mavenVersionOption: 'Default'
              effectivePomSkip: false
              sonarQubeRunAnalysis: false