trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stageCompile
    jobs:
      - job: jobCompile
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'deploy' # Optional
              publishJUnitResults: true
              javaHomeOption: '1.8'
